# Generated by Django 4.2.7 on 2023-12-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0002_remove_blog_dislikes"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
